This is a testharness.js-based test.
FAIL ensure create credential times out promise_test: Unhandled rejection with value: object "Error: timed out"
Harness: the test ran to completion.

