This is a testharness.js-based test.
FAIL createAnswer() with null remoteDescription should reject with InvalidStateErrorassert_unreached: Should have rejected: undefined Reached unreachable code
FAIL createAnswer() after setting remote description should succeedpromise_test: Unhandled rejection with value: object "OperationError: TEST_ERROR"
FAIL createAnswer() when connection is closed reject with InvalidStateErrorpromise_test: Unhandled rejection with value: object "OperationError: TEST_ERROR"
Harness: the test ran to completion.

